// <auto-generated />
namespace DietPlanner.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class migration005 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration005));
        
        string IMigrationMetadata.Id
        {
            get { return "201601031231456_migration005"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
